name: Triggered Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: gopalbackend-deployment-group
  cancel-in-progress: false

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy step"

  trigger-cdk-repo-workflow:
    runs-on: ubuntu-latest
    needs: dummy-job
    steps:
      - name: Trigger workflow in CDK repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/congpham234/GoPalBackendCDK/dispatches \
            -d '{"event_type": "trigger-workflow", "client_payload": {"COMMIT_MESSAGE": "GoPalBackend - ${{ github.event.head_commit.message }}"}}'
              